name: Publish

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: publish-to-conda
      uses: amauryval/publish_conda_package_action@1.0.0
      with:
        # CondaDir: locate the directory containing your meta.yml, conda_build_config.yaml (...) files
        CondaDir: 'conda'
        # Channels: You can add more channel with a space separator
        Channels: 'conda-forge niaorg/label/rc'
        # Platforms: remove one or more of these platforms
        Platforms: 'osx-64 linux-32 linux-64 win-32 win-64'
        CondaUsername: ${{ secrets.CONDA_USERNAME }}
        CondaPassword: ${{ secrets.CONDA_PASSWORD }}
